name: Impresiones en Consola

on:
  push:
    branches:
      - main
      - javi/tarea8
  pull_request:
    branches:
      - main

jobs:
  imprimir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar Python
        run: |
          python3 - <<EOF
          print("Hola desde Python")
          print("Python está corriendo dentro del workflow")
          print("Todo funcionando correctamente :)")
          EOF

      - name: Impresiones en consola
        run: |
          echo "Impresión 1"
          echo "Impresión 2"
          echo "Impresión 3"